# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8dfc4d7a0f87bdf378dcb3c4d58be545e400ae7376efca5eb6b3429f7c11eebbd6657f8c491afe12b97721ac6daf9205358f0ad4c67e7eed1150655e9834202

test:
  secret_key_base: e31542821bf49ca3028c2b0c9f6879f3bdc7007cdc76b6e85006c51b72d04eddab23bdb71c52997f2ade4e63e58007025d0c6f0341f44cc4aa25aca934b306a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
